version: "3.8"

services:
  churnsense:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - CHURNSENSE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
